var listing_mall = [
	{"title":"Aiming for the Stars",
	"desc":"Nip-slip (dudes apply) (+2)"},
	{"title":"Where are your Parents?!",
	"desc":"Kid at least 20 ft. from parents, under 4 years old (+2)"},
	{"title":"Beauty Zombie",
	"desc":"Person falls for the attractive kiosk advertiser showing off beauty products (+1)"},
	{"title":"Poppin' Out Like Popcorn",
	"desc":"At least 3 children to one stroller (+2)"},
	{"title":"Giant",
	"desc":"Person over 6'4 (+2)"},
	{"title":"Ouch!",
	"desc":"Booty slap that resonates LOUDLY (+2)"},
	{"title":"Product Zombie",
	"desc":"Someone has purchased a product being advertised in store (DOES NOT COUNT FOOD COURT)(+1)"},
	{"title":"Air Ball",
	"desc":"Someone tries to b-ball their trash (+1)<br/>If it makes it (+2)"},
	{"title":"This is Awkwaaaaaaaaard",
	"desc":"Stranger looks at you on at least 3+ takes (+2)"},
	{"title":"You know you're a 90's kid if...",
	"desc":"Someone wearing a product that is CLEARLY from the era 1990 - 2000 (+2)"},
	{"title":"Which way is...",
	"desc":"A business dad asking for directions (+2)"},
	{"title":"Makin' Oooooooout?",
	"desc":"Couple makes out for at least 10 seconds (+2)"},
	{"title":"Dropping an Ant",
	"desc":"Child/teenager drops an item from an upper floor (+2)"},
	{"title":"Mom of the Year",
	"desc":"Mother simultaneously policing 3+ children alone"},
	{"title":"Beardocalypse",
	"desc":"Beard reaching to at least abs (+2)"},
	{"title":"Amazing",
	"desc":"Someone actually wins at a prize grab machine"},
	{"title":"Gangsta Baby",
	"desc":"A G holding a baby (+2)"},
	{"title":"Shopaholic",
	"desc":"Holding 3+ bags (+1)"},
	{"title":"Choo choo daddy",
	"desc":"Adult on train (+1)"},
	{"title":"Off-time Appeal",
	"desc":"Employee in work clothes but not working (+1)"},
	{"title":"Let me carry those",
	"desc":"Dude carrying all of his lady's bags, trailing behind (+2)"},
	{"title":"Scrubs",
	"desc":"Wearing them (+1)"},
	{"title":"Marathoner",
	"desc":"Takes manual stairs (+1)"},
	{"title":"Chica Troopa",
	"desc":"4+ sassy chicas (+2)"},
	{"title":"Ahead of the Pack",
	"desc":"With a group, but 10 ft.+ ahead of them (+2)"},
	{"title":"Hardcore Blingah",
	"desc":"Bling on at least two surfaces (NOT REPEATED) (+2)"},
	{"title":"Watch out for that--!",
	"desc":"Runs into object (+2)"},
	{"title":"Frozen in Time",
	"desc":"At least three lines from a Frozen song (+2)"},
	{"title":"Why Even Buy?!",
	"desc":"Full bit of main course thrown away, at least 1/2 left (+2)"},
	{"title":"Haven't I Seen You Before?",
	"desc":"See the same person in 4 individual occurrences (+3)"}
];